### ISSUE TITLE
Azure Media Player

### ISSUE THREAD

**Issue by awatertrevi** [sdesyllas/hls-proxy-aes-service#4]
First of all, @sdesyllas thanks for providing this awesome example!

I am trying to implement your proxy with AMP (Azure Media Player http://ampdemo.azureedge.net/).

However without much luck. I keep getting the error: "No compatible source was found for this media"

I understand that your example was made for HLS.JS, but I was wondering if you ever attempted to use it in combination with AMP.

Thanks!

**Comment by sdesyllas** [comment]
Hi,

this is an example with HLS and AES encyption with bearer token using AMP:
http://ampdemo.azureedge.net/azuremediaplayer.html?url=https%3A%2F%2Famssamples.streaming.mediaservices.windows.net%2F830584f8-f0c8-4e41-968b-6538b9380aa5%2FTearsOfSteelTeaser.ism%2Fmanifest&aes=true&aestoken=Bearer%3DeyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1cm46bWljcm9zb2Z0OmF6dXJlOm1lZGlhc2VydmljZXM6Y29udGVudGtleWlkZW50aWZpZXIiOiI5ZGRhMGJjYy01NmZiLTQxNDMtOWQzMi0zYWI5Y2M2ZWE4MGIiLCJpc3MiOiJodHRwOi8vdGVzdGFjcy5jb20vIiwiYXVkIjoidXJuOnRlc3QiLCJleHAiOjE3MTA4MDczODl9.lJXm5hmkp5ArRIAHqVJGefW2bcTzd91iZphoKDwa6w8

And the HTML/js example is the following : 
 `
var myOptions = {
	"nativeControlsForTouch": false,
	controls: true,
	autoplay: true,
	width: "640",
	height: "400",
}
myPlayer = amp("azuremediaplayer", myOptions);
myPlayer.src([
        {
                "src": "https://azneccmediaq001-euno.streaming.media.azure.net/64d8e168-58e5-4df4-add7-63014955c782/CONT1000000001705811_vuplaysemiprod_movie_sd_devices_nodrm_SD_2.0EN.ism/manifest",
                "type": "application/vnd.apple.mpegurl",
                "streamingFormats": [
                        "HLS-V4",
                        "HLS-V3"
                ],
                "protectionInfo": [
                        {
                                "type": "AES",
                                "authenticationToken": "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyZXNvbHV0aW9uIjoicHJpdmF0ZTpTRCIsInJlZ2lvbiI6InVrIiwicGxhdGZvcm1jbGFzcyI6IldFQiIsInBsYXRmb3Jtc3ViY2xhc3MiOiJwcml2YXRlOnNhZmFyaSIsInVybjptaWNyb3NvZnQ6YXp1cmU6bWVkaWFzZXJ2aWNlczpjb250ZW50a2V5aWRlbnRpZmllciI6ImVlOTRiNjZjLWJlYTYtNGFiMC1hZjgwLWViNjBkODFjYWQ3YyIsImlzcyI6Imh0dHBzOi8vd3d3LnZ1YmlxdWl0eS5jb20vIiwiYXVkIjoidXJuOnZ1YmlxdWl0eSIsImV4cCI6MTU1MTM1NjIwM30.YKJP2W_mLKdrY7ra3F0PekgrVMdF3hHYihZdhEugkYw"
                        }
                ]
        }
]);
`

Hope that helps!

Spyros

**Comment by awatertrevi** [comment]
Thanks for your help!

It turns out I was trying it out in browser that didn't support HLS (Chrome for Mac).

Once I ran it in Safari it all worked.

**Comment by sdesyllas** [comment]
Yes , that's correct the browser needs to support hls natively, if it
doesn't support his you have to use hls.js, unfortunately amp doesn't wrap
hls.js and only works on browsers that support it natively
